export const FETCH_MEDICAL_RECORDS_REQUEST = "FETCH_MEDICAL_RECORDS_REQUEST";
export const FETCH_MEDICAL_RECORDS_SUCCESS = "FETCH_MEDICAL_RECORDS_SUCCESS";
export const FETCH_MEDICAL_RECORDS_FAILURE = "FETCH_MEDICAL_RECORDS_FAILURE";
