export enum Language {
  English = "EN",
  Danish = "DK",
  Lithuanian = "LT",
  Bulgarian = "BG",
}

export enum TypeOfRecord {
  Diagnosis = "DIAGNOSIS",
  GeneralVisit = "GENERAL_VISIT",
  Bloodwork = "BLOODWORK",
  MedicalImaging = "MEDICAL_IMAGING",
  Other = "Other",
}

export enum Country {
  Denmark = "DENMARK",
  Lithuania = "LITHUANIA",
  Bulgaria = "BULGARIA",
  USA = "USA",
  Canada = "CANADA",
  Germany = "GERMANY",
  France = "FRANCE",
  Italy = "ITALY",
  Spain = "SPAIN",
  UnitedKingdom = "UNITED KINGDOM",
  Sweden = "SWEDEN",
  Norway = "NORWAY",
  Finland = "FINLAND",
  Poland = "POLAND",
  Australia = "AUSTRALIA",
  Brazil = "BRAZIL",
  China = "CHINA",
  India = "INDIA",
  Japan = "JAPAN",
  SouthKorea = "SOUTH KOREA",
  Russia = "RUSSIA",
  SouthAfrica = "SOUTH AFRICA",
  Mexico = "MEXICO",
  Indonesia = "INDONESIA",
  Netherlands = "NETHERLANDS",
  Belgium = "BELGIUM",
  Greece = "GREECE",
  Portugal = "PORTUGAL",
  Austria = "AUSTRIA",
  Switzerland = "SWITZERLAND",
  Turkey = "TURKEY",
  Egypt = "EGYPT",
  SaudiArabia = "SAUDI ARABIA",
  Iran = "IRAN",
  Pakistan = "PAKISTAN",
  Argentina = "ARGENTINA",
  Chile = "CHILE",
  Peru = "PERU",
  Colombia = "COLOMBIA",
  Nigeria = "NIGERIA",
  Ethiopia = "ETHIOPIA",
  Ghana = "GHANA",
  Kenya = "KENYA",
  Uganda = "UGANDA",
  Tanzania = "TANZANIA",
  Zambia = "ZAMBIA",
  Zimbabwe = "ZIMBABWE",
  Vietnam = "VIETNAM",
  Thailand = "THAILAND",
  Malaysia = "MALAYSIA",
  Singapore = "SINGAPORE",
  Philippines = "PHILIPPINES",
  NewZealand = "NEW ZEALAND",
  Ireland = "IRELAND",
  Iceland = "ICELAND"
}

export enum DurationType {
  Days = "DAYS",
  Weeks = "WEEKS",
  Months = "MONTHS",
  Years = "YEARS",
  Indefinetely = "INDEFINETELY",
}
